# Introduction Python

## Tuples, Lists, Dictionaries, Arrays

In [4]:
from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 90%; }
    div#menubar-container     { width: 90%; }
    div#maintoolbar-container { width: 90%; }
</style>
"""))

In [ ]:
## 1.0 Types of variables 

a1 = 3.141
type(a1)

a2 = 3.1416165516
type(a2)

# from float to int 

c = int(a2)
type(c)

b1 = 10000
type(b1)

# from int to float 

float(b1)

b2 = 8
type(b2)

c1 = "My first python code"
print(c1)  # show that varaible's content
type(c1) # providing varaibles's type 

c2 = 'Lab1 Pucp'
print(c2)

type(c2)

# including a space using \n

c1 = "First python code"
print(c1,'\n')

# join string 

print(c1 + ":" + c2)

# f-using 


print(f'{c1} : semester 2022-1')

d = 2022

print(f'{c1} : semester {d}-1')

print('{} : semester {}-1'.format(c1,d))

#Using % string 

print("%s : semester %s -1" % (c1,d))

c1

c1[0:5]

#first character
print('Fisrt letter is :',c1[0])

#first word
print('Fisrt word is :',c1[0:5])

# triple quotes string can extend multiple lines
my_string = """Hello, welcome to
             the world of Python"""
print(my_string)

### 2. 0 Bool variables 

It’s used to represent the truth value of an expression.

"a" == "a"

1 > 1

z1 = (1==1)
z1

int(z1)

z1 = int(z1)
print(z1)

z2 = (10 > 20)
int(z2)

z3 = (100 != 100)
int(z3)

## 3.0 Tuple

#### It is an ordered and immutable Python object

T1 = (1,4,8,10,20,15,4,5,3,8)

type(T1)

# aritmethic operations

print('Suma:', sum(T1),"\n", "Minimo:", min(T1), '\n', "Maximo:", max(T1))

len(T1) # lenght of tuple

T1[0:5] # give us elements from 0 position until 4 position 

T1[1] # get tuple's element 

T1[0:3]

# 0 : first element
# end - 1 element

# It is not possible to change
T1[0] = 4

# count times of 8
T1.count(8)

T1[-1]

#position
T1.index(8)

T2 = ("alex", 5, True)
len(T2[0])

## 4.0 List

#### It is an ordered and mutable Python container.

L1 = []
print(L1)

dis1 = ["ATE", 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO']
dis1

dis2 = ['ATE', 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO','CHACLACAYO','CHORRILLOS','CIENEGUILLA'
        ,'COMAS','EL_AGUSTINO','INDEPENDENCIA']

len(dis2)

dis2[0]

print(type(dis2))

dis2[0]

dis2[2:5]   #(5-1=4)

dis2[3:7]

type(dis2[-1])

dis2[-5:-1]

len(dis2)

num = [13,5,5,8,9,10,5,8,13,1,20]
num.sort()
print(num)

num.append(102)
print(num)

num2 = [10,20,30]
num.extend(num2)
print(num)

print(num.index(102))

print("Suma:", sum(num),'\n', "Minimo:", min(num), '\n', "Maximo:", max(num))

import numpy as np


list1 = [ np.array([1,2,3]), "R", 120]

list1[0]

# from tuple to list 
T3 = (1,4,8,10,20,15,4,5,8,8)
#list(range(0,10))
T3 = list(T3)

print(list(T2))
T2 = ("alex", 5, True)
type(T2[2])
# No use list as a object´s name 

## 5.0 Dictionarities



Postal_code = {'Majes': 40520, 'Mollendo': 40701, 'Islay': 40704, 'Cotahuasi': 40801, 'Alca': 40802 }
type(Postal_code)

Postal_code

Postal_code['Alca']

Postal_code.clear()
print( Postal_code )

Postal_code = {'Majes': 40520, 'Mollendo': 40701,
               'Islay': 40704, 'Cotahuasi': 40801, 
               'Alca': 40802 }

# Get information from key
Postal_code.keys()
Postal_code.get('Islay')

Postal_code['Islay']

# Drop key
Postal_code.pop('Islay')
Postal_code

Postal_code.update( { "CHARCANA" :  40803 } )

Postal_code.update( {"LOMAS": {"UBIGEO": 40311, "Poverty Rate" : "18.2%", "Population" : "20 mil"}})

Postal_code.get('LOMAS').get('Poverty Rate')

Postal_code['LOMAS']['Poverty Rate']

# keys
cities = ['Fray Martin','Santa Rosa de Puquio','Cuchicorral','Santiago de Punchauca','La Cruz (11 Amigos)','Cerro Cañon','Cabaña Suche','San Lorenzo','Jose Carlos Mariategui','Pascal','La Esperanza','Fundo Pancha Paula','Olfa','Rio Seco','Paraiso','El Rosario','Cerro Puquio','La Campana','Las Animas','Vetancio','Roma Alta','San Jose','San Pedro de Carabayllo','Huacoy','Fundo Pampa Libre','Ex Fundo Santa Ines','Reposo','Carmelito','Santa Elena','Don Luis','Santa Ines Parcela','Asociacion Santa Ines','Roma Baja','Residencial Santa Lucia','San Francisco','Santa Margarita - Molinos','Sipan Peru','Fundo Cuadros','Bello Horizonte','El Hueco','Ex Fundo Mariategui','Naranjito','Vista Hermosa','El Sabroso de Jose Carlos Mariategui','Granja Carabayllo','Agropecuario Valle el Chillon','Camino Real','Copacabana','El Trebol','Tablada la Virgen','San Fernando de Carabayllo','San Fernando de Copacabana','La Manzana','Chacra Grande','Torres de Copacabana','San Pedro de Carabayllo','San Lorenzo','Chaclacayo','Chorrillos','Cieneguilla','Lindero','Pichicato','San Isidro','San Vicente','Piedra Liza','Santa Rosa de Chontay (Chontay)','La Libertad','El Agustino','Independencia','Jesus Maria','La Molina','La Victoria','Lince','Las Palmeras','Chosica','Lurin','Los Almacigos','Rinconada del Puruhuay','Fundo Santa Genoveva','Los Maderos','Casco Viejo','Vista Alegre','Buena Vista Alta','Lomas Pucara','Fundo la Querencia','Magdalena del Mar','Pueblo Libre','Miraflores','Pachacamac','Puente Manchay','Tambo Inga','Pampa Flores','Manchay Alto Lote B','Invasion Cementerio','Manchay Bajo','Santa Rosa de Mal Paso','Cardal','Jatosisa','Tomina','Pucusana','Honda','Quipa','Los Pelicanos','Playa Puerto Bello','Ñaves','Granja Santa Elena','Alvatroz II','Poseidon - Lobo Varado','Playa Minka Mar','Playa Acantilado','Puente Piedra','Punta Hermosa','Capilla Lucumo','Cucuya','Pampapacta','Avicola San Cirilo de Loma Negra - 03','Avicola San Cirilo de Loma Negra - 02','Avicola San Cirilo de Loma Negra - 01','Pampa Mamay','Cerro Botija','Agricultores y Ganaderos','Pampa Malanche Avicola Puma','Punta Negra','Chancheria','Rimac','San Bartolo','Plantel 41','Granja 4','Granja 5','Granja 07','Granja 44','Granja 47','Santa Maria I','Las Torres Santa Fe','San Francisco de Borja','San Isidro','San Juan de Lurigancho','Ciudad de Dios','San Luis','Barrio Obrero Industrial','San Miguel','Santa Anita - los Ficus','Santa Maria del Mar','Don Bruno','Santa Rosa','Santiago de Surco','Surquillo','Villa el Salvador','Villa Maria del Triunfo', 'Pueblo libre']
# values
postal_code1 = [15001,15003,15004,15006,15018,15019,15046,15072,15079,15081,15082,15083,15088,15123,15004,15011,15012,15019,15022,15023,15026,15476,15479,15483,15487,15491,15494,15498,15047,15049,15063,15082,15083,15121,15122,15313,15316,15318,15319,15320,15321,15324,15320,15320,15320,15320,15320,15320,15121,15320,15320,15121,15320,15320,15121,15121,15122,15122,15121,15121,15121,15320,15320,15320,15320,15320,15320,15121,15121,15121,15320,15121,15319,15121,15121,15121,15320,15320,15121,15121,15121,15121,15320,15320,15320,15122,15122,15122,15122,15122,15122,15122,15122,15121,15121,15122,15122,15121,15121,15122,15122,15121,15122,15122,15122,15472,15476,15054,15056,15057,15058,15063,15064,15066,15067,15593,15594,15593,15593,15593,15593,15593,15593,15593,15311,15312,15313,15314,15316,15324,15326,15327,15328,15332,15003,15004,15006,15007,15008,15009,15011,15018,15022,15311,15328,15331,15332,15333,15046, 15001]

# Return a dictionarie
ct_pc = dict( zip( cities , postal_code1) )

ct_pc

## 6.0 Numpy (array, matrices)

A library is a collection of modules or a single module. Libraries are the tools we will use to make our program.

import numpy as np
#import pandas as pd

# 1D array
a = np.array( [1, 2, 3, 4, 5] )
a
#type(a)

np.mean(a)

Standar deviation in Python by default

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N}}
\end{equation}

np.std(a)

Standar deviation in Python by default

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N-1}}
\end{equation}

np.std(a,ddof=1)

# 2D array
M = np.array( [ [1, 2, 3], [4, 5, 6] ] )

print(M)
type(M)

np.mean(M)

print(np.mean(M, axis=0)) # vertical operation axis = 0

print(np.mean(M, axis=1)) # horizontal operation axis = 1

print("Rows:",M.shape[0],"\n", "Columns: ", M.shape[1])


# Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 2:
y = np.arange( 0, 20, 2 )
print(y.shape)
print(y)

y[0]

# deafult one by one 

y = np.arange( 1, 11)
y

for i in np.arange(1,11):
    print(i)

A = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])

A

A[2:5,:]  # rows selecrtion


A[:,0:6]  # columns selecrtion

M1 = np.zeros( (8, 2) )
print(M1)

M2 = np.ones( (8, 4) )
print(M2)

## Join matrix

M3 = np.hstack((M1,M2))
M3


#vstack

con1 = np.concatenate((M1,M2), axis = 1) # add more columns. This is a horizontal operation
con1

M4 = np.array([[2,2,3,4,5,1],[1,5,5,9,8,2]])
print(M4)

M5 = np.vstack((M3,M4))
print(M5)
M5.T

con2 = np.concatenate((M3,M4), axis = 0) # add more rows. This is a vertical operation
con2

# Create a 1D NumPy array of ones of length 10:
w = np.ones(10)
print(w)
type(w)

# Create the identity matrix of size 8:
I = np.eye(8)
print(I)



I3 = I.reshape(32, 2)
print(I3)

#Transpose
print(I3.T)
(I3.T).shape

import random 

random.seed(175)

x1 = np.random.rand(500) # uniform distribution  [0,1]
x2 = np.random.rand(500) # uniform distribution [0,1]
x3 = np.random.rand(500) # uniform distribution [0,1]
x4 = np.random.rand(500) # uniform distribution [0,1]
e = np.random.normal(0,1,500) # normal distribution mean = 0 and sd = 1

# Poblacional regression (Data Generating Process GDP)


Y = 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e

X = np.column_stack((np.ones(500),x1,x2,x3,x4))
X

beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )


In [4]:
a1 = 3.141
type(a1)

float

In [7]:
a2 = 3.1416165516
type(a2)

float

In [9]:
# from float to int 

c = int(a2)
type(c)

int

In [10]:
b1 = 10000
type(b1)

int

In [11]:
# from int to float 

float(b1)

10000.0

In [6]:
b2 = 8
type(b2)

int

In [15]:
c1 = "My first python code"
print(c1)  # show that varaible's content
type(c1) # providing varaibles's type 

My first python code


str

In [16]:
c2 = 'Lab1 Pucp'
print(c2)

Lab1 Pucp


In [9]:
type(c2)

str

In [18]:
# including a space using \n

c1 = "First python code"
print(c1,'\n')

First python code 



In [21]:
# join string 

print(c1 + ":" + c2)

First python code:Lab1 Pucp


In [25]:
# f-using 


print(f'{c1} : semester 2022-1')

First python code : semester 2022-1


In [26]:
d = 2022

In [29]:
print(f'{c1} : semester {d}-1')

First python code : semester 2022-1


In [30]:
print('{} : semester {}-1'.format(c1,d))

First python code : semester 2022-1


In [31]:
#Using % string 

print("%s : semester %s -1" % (c1,d))

First python code : semester 2022 -1


In [32]:
c1

'First python code'

In [34]:
c1[0:5]

'First'

In [17]:
#first character
print('Fisrt letter is :',c1[0])

Fisrt letter is : F


In [35]:
#first word
print('Fisrt word is :',c1[0:5])

Fisrt word is : First


In [36]:
# triple quotes string can extend multiple lines
my_string = """Hello, welcome to
             the world of Python"""
print(my_string)

Hello, welcome to
             the world of Python


### 2. 0 Bool variables 

It’s used to represent the truth value of an expression.

In [38]:
"a" == "a"

True

In [40]:
1 > 1

False

In [41]:
z1 = (1==1)
z1

True

In [43]:
int(z1)

1

In [24]:
z1 = int(z1)
print(z1)

1


In [25]:
z2 = (10 > 20)
int(z2)

0

In [44]:
z3 = (100 != 100)
int(z3)

0

## 3.0 Tuple

#### It is an ordered and immutable Python object

In [49]:
T1 = (1,4,8,10,20,15,4,5,3,8)

type(T1)

tuple

In [52]:
# aritmethic operations

print('Suma:', sum(T1),"\n", "Minimo:", min(T1), '\n', "Maximo:", max(T1))

Suma: 78 
 Minimo: 1 
 Maximo: 20


In [53]:
len(T1) # lenght of tuple

10

In [62]:
T1[0:5] # give us elements from 0 position until 4 position 

(1, 4, 8, 10, 20)

In [30]:
T1[1] # get tuple's element 

4

In [31]:
T1[0:3]

# 0 : first element
# end - 1 element

(1, 4, 8)

In [63]:
# It is not possible to change
T1[0] = 4

TypeError: 'tuple' object does not support item assignment

In [64]:
# count times of 8
T1.count(8)

2

In [70]:
T1[-1]

8

In [68]:
#position
T1.index(8)

2

In [35]:
T2 = ("alex", 5, True)
len(T2[0])

4

## 4.0 List

#### It is an ordered and mutable Python container.

In [72]:
L1 = []
print(L1)

[]


In [73]:
dis1 = ["ATE", 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO']
dis1

['ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO']

In [74]:
dis2 = ['ATE', 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO','CHACLACAYO','CHORRILLOS','CIENEGUILLA'
        ,'COMAS','EL_AGUSTINO','INDEPENDENCIA']

In [78]:
len(dis2)

11

In [79]:
dis2[0]

'ATE'

In [80]:
print(type(dis2))

<class 'list'>


In [41]:
dis2[0]

'ATE'

In [82]:
dis2[2:5]   #(5-1=4)

['BREÑA', 'CALLAO', 'CARABAYLLO']

In [83]:
dis2[3:7]

['CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS']

In [84]:
type(dis2[-1])

str

In [44]:
dis2[-5:-1]

['CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO']

In [45]:
len(dis2)

11

In [85]:
num = [13,5,5,8,9,10,5,8,13,1,20]
num.sort()
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20]


In [86]:
num.append(102)
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20, 102]


In [48]:
num2 = [10,20,30]
num.extend(num2)
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20, 102, 10, 20, 30]


In [87]:
print(num.index(102))

11


In [88]:
print("Suma:", sum(num),'\n', "Minimo:", min(num), '\n', "Maximo:", max(num))

Suma: 199 
 Minimo: 1 
 Maximo: 102


In [91]:
import numpy as np


list1 = [ np.array([1,2,3]), "R", 120]

list1[0]

array([1, 2, 3])

In [52]:
# from tuple to list 
T3 = (1,4,8,10,20,15,4,5,8,8)
#list(range(0,10))
T3 = list(T3)

print(list(T2))
T2 = ("alex", 5, True)
type(T2[2])
# No use list as a object´s name 

['alex', 5, True]


bool

## 5.0 Dictionarities



In [93]:
Postal_code = {'Majes': 40520, 'Mollendo': 40701, 'Islay': 40704, 'Cotahuasi': 40801, 'Alca': 40802 }
type(Postal_code)

dict

In [94]:
Postal_code

{'Majes': 40520,
 'Mollendo': 40701,
 'Islay': 40704,
 'Cotahuasi': 40801,
 'Alca': 40802}

In [97]:
Postal_code['Alca']

40802

In [55]:
Postal_code.clear()
print( Postal_code )

{}


In [98]:
Postal_code = {'Majes': 40520, 'Mollendo': 40701,
               'Islay': 40704, 'Cotahuasi': 40801, 
               'Alca': 40802 }

In [99]:
# Get information from key
Postal_code.keys()
Postal_code.get('Islay')

40704

In [100]:
Postal_code['Islay']

40704

In [101]:
# Drop key
Postal_code.pop('Islay')
Postal_code

{'Majes': 40520, 'Mollendo': 40701, 'Cotahuasi': 40801, 'Alca': 40802}

In [102]:
Postal_code.update( { "CHARCANA" :  40803 } )

Postal_code.update( {"LOMAS": {"UBIGEO": 40311, "Poverty Rate" : "18.2%", "Population" : "20 mil"}})

In [60]:
Postal_code.get('LOMAS').get('Poverty Rate')

'18.2%'

In [105]:
Postal_code['LOMAS']['Poverty Rate']

'18.2%'

In [62]:
# keys
cities = ['Fray Martin','Santa Rosa de Puquio','Cuchicorral','Santiago de Punchauca','La Cruz (11 Amigos)','Cerro Cañon','Cabaña Suche','San Lorenzo','Jose Carlos Mariategui','Pascal','La Esperanza','Fundo Pancha Paula','Olfa','Rio Seco','Paraiso','El Rosario','Cerro Puquio','La Campana','Las Animas','Vetancio','Roma Alta','San Jose','San Pedro de Carabayllo','Huacoy','Fundo Pampa Libre','Ex Fundo Santa Ines','Reposo','Carmelito','Santa Elena','Don Luis','Santa Ines Parcela','Asociacion Santa Ines','Roma Baja','Residencial Santa Lucia','San Francisco','Santa Margarita - Molinos','Sipan Peru','Fundo Cuadros','Bello Horizonte','El Hueco','Ex Fundo Mariategui','Naranjito','Vista Hermosa','El Sabroso de Jose Carlos Mariategui','Granja Carabayllo','Agropecuario Valle el Chillon','Camino Real','Copacabana','El Trebol','Tablada la Virgen','San Fernando de Carabayllo','San Fernando de Copacabana','La Manzana','Chacra Grande','Torres de Copacabana','San Pedro de Carabayllo','San Lorenzo','Chaclacayo','Chorrillos','Cieneguilla','Lindero','Pichicato','San Isidro','San Vicente','Piedra Liza','Santa Rosa de Chontay (Chontay)','La Libertad','El Agustino','Independencia','Jesus Maria','La Molina','La Victoria','Lince','Las Palmeras','Chosica','Lurin','Los Almacigos','Rinconada del Puruhuay','Fundo Santa Genoveva','Los Maderos','Casco Viejo','Vista Alegre','Buena Vista Alta','Lomas Pucara','Fundo la Querencia','Magdalena del Mar','Pueblo Libre','Miraflores','Pachacamac','Puente Manchay','Tambo Inga','Pampa Flores','Manchay Alto Lote B','Invasion Cementerio','Manchay Bajo','Santa Rosa de Mal Paso','Cardal','Jatosisa','Tomina','Pucusana','Honda','Quipa','Los Pelicanos','Playa Puerto Bello','Ñaves','Granja Santa Elena','Alvatroz II','Poseidon - Lobo Varado','Playa Minka Mar','Playa Acantilado','Puente Piedra','Punta Hermosa','Capilla Lucumo','Cucuya','Pampapacta','Avicola San Cirilo de Loma Negra - 03','Avicola San Cirilo de Loma Negra - 02','Avicola San Cirilo de Loma Negra - 01','Pampa Mamay','Cerro Botija','Agricultores y Ganaderos','Pampa Malanche Avicola Puma','Punta Negra','Chancheria','Rimac','San Bartolo','Plantel 41','Granja 4','Granja 5','Granja 07','Granja 44','Granja 47','Santa Maria I','Las Torres Santa Fe','San Francisco de Borja','San Isidro','San Juan de Lurigancho','Ciudad de Dios','San Luis','Barrio Obrero Industrial','San Miguel','Santa Anita - los Ficus','Santa Maria del Mar','Don Bruno','Santa Rosa','Santiago de Surco','Surquillo','Villa el Salvador','Villa Maria del Triunfo', 'Pueblo libre']
# values
postal_code1 = [15001,15003,15004,15006,15018,15019,15046,15072,15079,15081,15082,15083,15088,15123,15004,15011,15012,15019,15022,15023,15026,15476,15479,15483,15487,15491,15494,15498,15047,15049,15063,15082,15083,15121,15122,15313,15316,15318,15319,15320,15321,15324,15320,15320,15320,15320,15320,15320,15121,15320,15320,15121,15320,15320,15121,15121,15122,15122,15121,15121,15121,15320,15320,15320,15320,15320,15320,15121,15121,15121,15320,15121,15319,15121,15121,15121,15320,15320,15121,15121,15121,15121,15320,15320,15320,15122,15122,15122,15122,15122,15122,15122,15122,15121,15121,15122,15122,15121,15121,15122,15122,15121,15122,15122,15122,15472,15476,15054,15056,15057,15058,15063,15064,15066,15067,15593,15594,15593,15593,15593,15593,15593,15593,15593,15311,15312,15313,15314,15316,15324,15326,15327,15328,15332,15003,15004,15006,15007,15008,15009,15011,15018,15022,15311,15328,15331,15332,15333,15046, 15001]

In [63]:
# Return a dictionarie
ct_pc = dict( zip( cities , postal_code1) )

In [64]:
ct_pc

{'Fray Martin': 15001,
 'Santa Rosa de Puquio': 15003,
 'Cuchicorral': 15004,
 'Santiago de Punchauca': 15006,
 'La Cruz (11 Amigos)': 15018,
 'Cerro Cañon': 15019,
 'Cabaña Suche': 15046,
 'San Lorenzo': 15122,
 'Jose Carlos Mariategui': 15079,
 'Pascal': 15081,
 'La Esperanza': 15082,
 'Fundo Pancha Paula': 15083,
 'Olfa': 15088,
 'Rio Seco': 15123,
 'Paraiso': 15004,
 'El Rosario': 15011,
 'Cerro Puquio': 15012,
 'La Campana': 15019,
 'Las Animas': 15022,
 'Vetancio': 15023,
 'Roma Alta': 15026,
 'San Jose': 15476,
 'San Pedro de Carabayllo': 15121,
 'Huacoy': 15483,
 'Fundo Pampa Libre': 15487,
 'Ex Fundo Santa Ines': 15491,
 'Reposo': 15494,
 'Carmelito': 15498,
 'Santa Elena': 15047,
 'Don Luis': 15049,
 'Santa Ines Parcela': 15063,
 'Asociacion Santa Ines': 15082,
 'Roma Baja': 15083,
 'Residencial Santa Lucia': 15121,
 'San Francisco': 15122,
 'Santa Margarita - Molinos': 15313,
 'Sipan Peru': 15316,
 'Fundo Cuadros': 15318,
 'Bello Horizonte': 15319,
 'El Hueco': 15320,
 'Ex F

## 6.0 Numpy (array, matrices)

A library is a collection of modules or a single module. Libraries are the tools we will use to make our program.

In [106]:
import numpy as np
#import pandas as pd

In [107]:
# 1D array
a = np.array( [1, 2, 3, 4, 5] )
a
#type(a)

array([1, 2, 3, 4, 5])

In [108]:
np.mean(a)

3.0

Standar deviation in Python by default

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N}}
\end{equation}

In [109]:
np.std(a)

1.4142135623730951

Standar deviation in Python by default

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N-1}}
\end{equation}

In [111]:
np.std(a,ddof=1)

1.5811388300841898

In [112]:
# 2D array
M = np.array( [ [1, 2, 3], [4, 5, 6] ] )

print(M)
type(M)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [113]:
np.mean(M)

3.5

In [7]:
print(np.mean(M, axis=0)) # vertical operation axis = 0

print(np.mean(M, axis=1)) # horizontal operation axis = 1

[2.5 3.5 4.5]
[2. 5.]


In [8]:
print("Rows:",M.shape[0],"\n", "Columns: ", M.shape[1])


Rows: 2 
 Columns:  3


In [9]:
# Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 2:
y = np.arange( 0, 20, 2 )
print(y.shape)
print(y)

(10,)
[ 0  2  4  6  8 10 12 14 16 18]


In [10]:
y[0]

0

In [115]:
# deafult one by one 

y = np.arange( 1, 11)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
for i in np.arange(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [117]:
A = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])

In [118]:
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [14]:
A[2:5,:]  # rows selecrtion


array([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [120]:
A[:,0:6]  # columns selecrtion

array([[  0,   1,   2,   3,   4,   5],
       [ 10,  11,  12,  13,  14,  15],
       [ 30,  31,  32,  33,  34,  35],
       [-20, -19, -18, -17, -16, -15],
       [  2,   4,   6,   8,  10,  12]])

In [124]:
M1 = np.zeros( (8, 2) )
print(M1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [125]:
M2 = np.ones( (8, 4) )
print(M2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Join matrix

In [126]:
M3 = np.hstack((M1,M2))
M3


#vstack

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [127]:
con1 = np.concatenate((M1,M2), axis = 1) # add more columns. This is a horizontal operation
con1

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [206]:
M4 = np.array([[2,2,3,4,5,1],[1,5,5,9,8,2]])
print(M4)

[[2 2 3 4 5 1]
 [1 5 5 9 8 2]]


In [208]:
M5 = np.vstack((M3,M4))
print(M5)
M5.T

[[0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [2. 2. 3. 4. 5. 1.]
 [1. 5. 5. 9. 8. 2.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 2., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 4., 9.],
       [1., 1., 1., 1., 1., 1., 1., 1., 5., 8.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 2.]])

In [ ]:
con2 = np.concatenate((M3,M4), axis = 0) # add more rows. This is a vertical operation
con2

In [78]:
# Create a 1D NumPy array of ones of length 10:
w = np.ones(10)
print(w)
type(w)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


numpy.ndarray

In [79]:
# Create the identity matrix of size 8:
I = np.eye(8)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [80]:
I3 = I.reshape(32, 2)
print(I3)

[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [81]:
#Transpose
print(I3.T)
(I3.T).shape

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 1.]]


(2, 32)

In [135]:
import random 

random.seed(175)

x1 = np.random.rand(500) # uniform distribution  [0,1]
x2 = np.random.rand(500) # uniform distribution [0,1]
x3 = np.random.rand(500) # uniform distribution [0,1]
x4 = np.random.rand(500) # uniform distribution [0,1]
e = np.random.normal(0,1,500) # normal distribution mean = 0 and sd = 1

# Poblacional regression (Data Generating Process GDP)


Y = 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e

In [136]:
X = np.column_stack((np.ones(500),x1,x2,x3,x4))
X

array([[1.        , 0.36804363, 0.02294361, 0.24486573, 0.17290321],
       [1.        , 0.27712731, 0.79784676, 0.36029423, 0.44119249],
       [1.        , 0.82491002, 0.55395663, 0.88001848, 0.39545083],
       ...,
       [1.        , 0.54056608, 0.74168344, 0.29534668, 0.59413935],
       [1.        , 0.3030251 , 0.05738283, 0.77553227, 0.53724444],
       [1.        , 0.43975284, 0.95953193, 0.21344539, 0.3742862 ]])

In [239]:
beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )


array([0.95331358, 0.80952446, 1.13566675, 0.87588083, 1.31801947])

### Matriz generadora de residuos 

\begin{equation}
 M = I - X(X'X)^{-1}X
\end{equation}

# References

## Numpy 
https://numpy.org/doc/stable/reference/arrays.html

https://www.kaggle.com/code/hkumls/intensive-python-tutorial-numpy/notebook